
package Connection;

import java.sql.Connection;
import java.sql.DriverManager;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.sql.DataSource;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DBConnection.java
//  @ Date : 2016-11-1
//  @ Author : 
//
//
public class DBConnection {
	static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
	static final String DB_URL = "jdbc:mysql://localhost:3306/flook";
	//static final String DB_URL = "jdbc:mysql://kwongiho.iptime.org:3306/flook";
//27.117.242.131
	static final String USERNAME = "root";
	static final String PASSWORD = "siddid";
	//static final String PASSWORD = AutoStatic.MYSQL_PWD;
	private static DBConnection instance;
	static {
		instance = new DBConnection();
	}
	public static DBConnection getInstance(){
		return instance;
	}
	Connection conn = null;
	public Connection getConn(){
		try {
			conn.setAutoCommit(false);
		} catch(Exception ex) {
			ex.printStackTrace();
		}
		
		return this.conn;
	}
	private DBConnection(){
		try{
			Class.forName(JDBC_DRIVER);
			conn = DriverManager.getConnection(DB_URL,USERNAME,PASSWORD);
		}
		catch(Exception ex) {
			ex.printStackTrace();
		}
	}
}
/*
 * try {
 * 
 * Class.forName("com.mysql.jdbc.Driver"); conn =
 * DriverManager.getConnection("jdbc:mysql://localhost:3306/RECALLDB","recall",
 * "recallpwd"); conn.setAutoCommit(false); } catch (Exception ex) {
 * ex.printStackTrace(); }
 */